version: "{build}"

environment:
  matrix:
    - NODEJS_VERSION: "18"

install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - npm install

build_script:
  - npm run build

test_script:
  - npm test